from dydx3.constants import API_HOST_GOERLI, API_HOST_MAINNET
from decouple import config

# MODE = "PRODUCTION"
MODE = "DEVELOPMENT"

# Resolution: Can be one of 1DAY, 4HOURS, 1HOUR, 30MINS, 15MINS, 5MINS, 1MIN.
RESOLUTION = "4HOURS"

# Strategy Setting
MARKET = "BTC-USD"
WINDOW1 = 20
WINDOW2 = 30
WINDOW3 = 40
WINDOW4 = 50
STOP_LOSS = 0.06
ATR_MULTIPLIER = 3
USD_PER_TRADE = 5000
USD_MIN_COLLATERAL = 8000


# Ethereum Address
ETHEREUM_ADDRESS = '0xb0F51EaC224235323c75a8B086F65362A0052C06'

# KEYS - PRODUCTION
# Must be on Mainnet in DYDX
STARK_PRIVATE_KEY_MAINNET = config("STARK_PRIVATE_KEY_MAINNET")
DYDX_API_KEY_MAINNET = config("DYDX_API_KEY_MAINNET")
DYDX_API_SECRET_MAINNET = config("DYDX_API_SECRET_MAINNET")
DYDX_API_PASSPHRASE_MAINNET = config("DYDX_API_PASSPHRASE_MAINNET")

# KEYS - DEVELOPMENT
# Must be on Testnet in DYDX
STARK_PRIVATE_KEY_TESTNET = config("STARK_PRIVATE_KEY_TESTNET")
DYDX_API_KEY_TESTNET = config("DYDX_API_KEY_TESTNET")
DYDX_API_SECRET_TESTNET = config("DYDX_API_SECRET_TESTNET")
DYDX_API_PASSPHRASE_TESTNET = config("DYDX_API_PASSPHRASE_TESTNET")

# KEYS - Export
STARK_PRIVATE_KEY = STARK_PRIVATE_KEY_MAINNET if MODE == "PRODUCTION" \
    else STARK_PRIVATE_KEY_TESTNET
DYDX_API_KEY = DYDX_API_KEY_MAINNET if MODE == "PRODUCTION" \
    else DYDX_API_KEY_TESTNET
DYDX_API_SECRET = DYDX_API_SECRET_MAINNET if MODE == "PRODUCTION" \
    else DYDX_API_SECRET_TESTNET
DYDX_API_PASSPHRASE = DYDX_API_PASSPHRASE_MAINNET if MODE == "PRODUCTION" \
    else DYDX_API_PASSPHRASE_TESTNET

# HOST - Export
HOST = API_HOST_MAINNET if MODE == "PRODUCTION" else API_HOST_GOERLI

# HTTP PROVIDER
HTTP_PROVIDER_MAINNET = "https://eth-mainnet.g.alchemy.com/v2/L60LQARdBU1g8c2Ninpdgk20lkZavUDy"
HTTP_PROVIDER_TESTNET = "https://eth-goerli.g.alchemy.com/v2/02AwF6WR5ui7RWKgpZ2BllcqDEQWBYIE"
HTTP_PROVIDER = HTTP_PROVIDER_MAINNET if MODE == "PRODUCTION" else HTTP_PROVIDER_TESTNET
